# Generated by Django 6.0 on 2025-12-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('resin', 'Resin Art'), ('custom', 'Customised Work'), ('chocolate', 'Chololate Box'), ('ScrapBook', 'Scrapbook')], max_length=50),
        ),
    ]
